import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/_components/shared/Header";
import ClientProvider from "./_provider/ClientProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-[#e1dfd6] min-h-screen dark:bg-slate-950">
          <ClientProvider>
            <Header />
            {children}
          </ClientProvider>
        </div>
      </body>
    </html>
  );
}
